# Generated by Django 3.0.8 on 2020-07-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('pan', models.IntegerField()),
                ('address', models.CharField(max_length=700)),
                ('loan_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
